In [4]:
import numpy as np 

# Array İşlemleri 

In [5]:
a = [1,2,3]
b = [2,4,8]

In [6]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
[2,4,8] * 3 

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [8]:
x = np.array(a)
y = np.array(b)

In [9]:
# element-wise multiplication 
x*y

array([ 2,  8, 24])

In [10]:
z = np.array([1,2,3,4])
x*z

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [11]:
a+b

[1, 2, 3, 2, 4, 8]

In [12]:
x+y

array([ 3,  6, 11])

In [13]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [14]:
3*x

array([3, 6, 9])

In [15]:
x

array([1, 2, 3])

In [16]:
x = x*3

In [17]:
x

array([3, 6, 9])

# Array Attribute'ları

In [18]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
y = np.zeros((2,5,6))
print(y)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [20]:
print(x.shape)
print(y.shape)

(2, 3)
(2, 5, 6)


In [21]:
print(x.ndim)
print(y.ndim)

2
3


In [22]:
print(x.size)
print(y.size)

6
60


In [23]:
print(x.dtype)

float64


# Reshaping
***Önemli nokta reshape yapacağımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması, yani size'ları aynı olacak.

In [24]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(a.ndim)
print(a.size)

1
10


In [26]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
a.reshape(2,5).ndim

2

In [29]:
# !!! eleman sayıları aynı olmalı 
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

# -1 İle Boyuta Karar Vermek 

In [30]:
# buradaki durum şu şekilde : 2 sütun olduğunu belirtiyoruz ve bizim belirttiğimiz değere göre bir satır ayarlamasını istiyoruz.
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
a.reshape(-1,3)

ValueError: cannot reshape array of size 10 into shape (3)

# Yeni Boyut Eklemek 

In [32]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
a.shape

(10,)

In [34]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [35]:
a[np.newaxis, :].ndim

2

In [36]:
# bu şekilde bir boyut eklemiş oluyoruyz
a[np.newaxis, :].shape

(1, 10)

In [37]:
# column vector
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [38]:
a[:, np.newaxis].shape

(10, 1)

veya None yazarak yukarıdaki işlemi yapabiliriz

In [39]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [40]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Concatenation

In [41]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [42]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
# list ile de birleştirebiliriz !
l = [10,11]

In [44]:
np.concatenate([l,a,b])

array([10, 11,  1,  2,  3,  4,  5,  6,  7,  8])

In [45]:
l2 = [10,11,12,11.2]
np.concatenate([l2,a,b])

array([10. , 11. , 12. , 11.2,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,
        8. ])

In [46]:
l3 = [10,11,12,"13"]
np.concatenate([l3,a,b])

array(['10', '11', '12', '13', '1', '2', '3', '4', '5', '6', '7', '8'],
      dtype='<U11')

In [47]:
# python tuple'larını verebiliriz
l = (111,112)
np.concatenate([l,a,b])

array([111, 112,   1,   2,   3,   4,   5,   6,   7,   8])

# Size Mismatch

In [48]:
a

array([1, 2, 3, 4])

In [49]:
x = np.array([[1,2,3],
              [4,5,6]])

In [50]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
print(x.size)
print(x.shape)

6
(2, 3)


In [52]:
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [53]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# default axis=0, yani satır satır ekleme yapar.
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Stack
***yeni dimension ekleyip o dimension üzerinde concatenation yaparak da sağlayabiliriz.

In [67]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

In [68]:
print(a)
print(b)

[1 2 3 4]
[6 7 8 9]


In [69]:
print(a.shape)
print(b.shape)

(4,)
(4,)


In [70]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [71]:
a = np.stack([a,b], axis=1)