In [3]:
import numpy as np

# Splitting

In [4]:
l = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [5]:
l

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [6]:
# ikinci ve altıncı indexten önce kesme işareti bırak ve o noktalardan parçala.
np.split(l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]

In [7]:
np.split(l, [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80, 90])]

In [8]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.split(a, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]

# Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [11]:
a, b = (1, 10)

In [12]:
print(a)
print(b)

1
10


In [13]:
x, y, z = np.split(l, [2,6])

In [14]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80 90]


# vsplit

In [15]:
a = np.arange(20).reshape(2, 10)

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
# vsplit: vertical split 
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [18]:
np.vsplit(a, [1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# hsplit 

In [19]:
a = np.arange(20).reshape(2, 10)

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [24]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [25]:
np.hsplit(a, [2])[1].shape

(2, 8)

In [26]:
np.hsplit(a, [2])[0].shape

(2, 2)

In [27]:
x, y, z = np.hsplit(a, [2,4])

In [29]:
print(x, end = "\n*********\n")
print(y, end = "\n*********\n")
print(z, end = "\n*********\n")

[[ 0  1]
 [10 11]]
*********
[[ 2  3]
 [12 13]]
*********
[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]
*********


# Sorting

In [30]:
a = np.array([20,32,5,30,10])

In [31]:
a

array([20, 32,  5, 30, 10])

In [32]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [33]:
a

array([20, 32,  5, 30, 10])

In [34]:
a.sort()

In [35]:
a

array([ 5, 10, 20, 30, 32])

# argsort

In [36]:
a = np.array([20,32,5,30,10])

In [37]:
a

array([20, 32,  5, 30, 10])

In [38]:
# Küçükten büyüğe sıralanmış elemanların indexlerini döndürür.
idxs = np.argsort(a)

In [39]:
idxs

array([2, 4, 0, 3, 1], dtype=int64)

# Multidimensional Array'lerin Elemanlarına Ulaşmak 

In [40]:
a = np.arange(1,21).reshape(4,5)

In [41]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
a[0]

array([1, 2, 3, 4, 5])

In [43]:
a[1]

array([ 6,  7,  8,  9, 10])

In [44]:
a[0][0]

1

In [45]:
a[2][1]

12

In [46]:
a[0,0]

1

In [47]:
a[1,1]

7

In [48]:
a[0,1]

2

In [49]:
a[1,1] = 10

In [50]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
a[1,1] = 20.40

In [52]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
a[1,1] = "30"

In [54]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
a[1,1] = "a"

ValueError: invalid literal for int() with base 10: 'a'

In [56]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Slice Indexing

In [57]:
a = np.arange(1,21).reshape(4,5)

In [58]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
a[1]

array([ 6,  7,  8,  9, 10])

In [60]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [62]:
a[:,0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [63]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [64]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [65]:
a[2,3]

14

In [66]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
a[:,3]

array([ 4,  9, 14, 19])

In [68]:
a[:,3].shape

(4,)

In [70]:
a[::2,3]

array([ 4, 14])

In [71]:
a[0,:]

array([1, 2, 3, 4, 5])

In [72]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
a[0, 2:4]

array([3, 4])

In [74]:
a[:2, :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [75]:
a[:, :4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [76]:
a = np.arange(1,13).reshape(3,4)

In [77]:
a[::2, :3]

array([[ 1,  2,  3],
       [ 9, 10, 11]])

# Fancy Indexing

In [78]:
x = np.arange(1, 15)

In [79]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
idxs = [4,5,7,11]

In [81]:
x[idxs]

array([ 5,  6,  8, 12])

In [82]:
a = np.arange(12).reshape(3,4)

In [83]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a[0:2, 1:3]

array([[1, 2],
       [5, 6]])

In [85]:
a[0, [1,3]]

array([1, 3])

In [86]:
a = np.arange(20).reshape(4,5)

In [87]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
idx1 = [1,3,2]
idx2 = [3,0,2]

In [93]:
a[idx1,idx2]

array([ 8, 15, 12])

In [95]:
a[idx1,idx2].shape

(3,)

In [96]:
a[idx1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [97]:
a[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [99]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
x[[1,2,3]] = 20

In [101]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
x = np.arange(9)

In [103]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
x[[1,2,5]] = [100,200,300]

In [105]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

In [106]:
idxs = [4,5,7,1]

In [107]:
x[idxs]

array([  4, 300,   7, 100])

In [108]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
a[0:2,1]

array([1, 6])

# Subarray

In [110]:
a = np.arange(1,21).reshape(4,5)

In [111]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [112]:
b = a[:2, :3]

In [113]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [114]:
b.ndim

2

In [115]:
b[0,0] = 100

In [116]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [117]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Copy

In [126]:
b = a[:2,:3].copy()

In [127]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [128]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [129]:
b[0,0] = 200

In [130]:
b

array([[200,   2,   3],
       [  6,   7,   8]])

In [131]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Conditional Indexing

In [136]:
a = np.arange(1,10)

In [137]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [139]:
a[a<5]

array([1, 2, 3, 4])

In [140]:
filt = a < 3

In [141]:
a[filt]

array([1, 2])

In [145]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
b = np.array([2,3,3,4,5,61,7,8,11])
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [147]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [144]:
a[a==b]

array([3, 4, 5, 7, 8])

In [148]:
b[a==b]

array([3, 4, 5, 7, 8])

In [149]:
# normalde and or ile kurduğumuz mantığı numpy'da kullanamıyoruz!
(a<3) or (a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [150]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [151]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [152]:
filt = (a<3) | (a>5)

In [153]:
a[filt]

array([1, 2, 6, 7, 8, 9])

# Filtrenin Değili

In [156]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [157]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
# ! işareti ile ters alma işlemi yapamıyoruz...
a[!(filt)]

SyntaxError: invalid syntax (<ipython-input-169-01c4dc164210>, line 2)

In [168]:
a[not(filt)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [165]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [166]:
a[~filt]

array([3, 4, 5])

# Multidimensional Array'lerde Conditional Indexing 

In [170]:
a = np.arange(1,21).reshape(4,5)

In [171]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [172]:
type(a)

numpy.ndarray

In [173]:
type(a<6)

numpy.ndarray

In [174]:
a[a<7].shape

(6,)

In [175]:
a = np.array([1,2,3,None])

In [176]:
a

array([1, 2, 3, None], dtype=object)

In [177]:
a[a==None]

array([None], dtype=object)

# Sum

In [178]:
a = np.arange(1,21).reshape(4,5)

In [179]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [180]:
np.sum(a)

210

In [181]:
filt = a < 5

In [182]:
np.sum(filt)

4

In [183]:
a[filt]

array([1, 2, 3, 4])

In [184]:
filt = ~((a>5) & (a<9))

In [185]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [186]:
np.sum(filt)

17

In [187]:
np.sum(a[filt])

189

# Belirli Axis Uzerinde Toplama

In [189]:
a 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [191]:
#sütun sütun toplar.
np.sum(a, axis=0)

array([34, 38, 42, 46, 50])

In [192]:
np.sum(a, axis=1)

array([15, 40, 65, 90])

In [ ]:
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)

print(numpy.prod(numpy.sum(A, axis=0), axis=0))