In [2]:
import numpy as np 

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array(["a","b","c","d","e"])

In [7]:
y

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [8]:
#bütün integer'lar string e dönüştürülecek 
z = np.array([1,2,3,"a"])

In [9]:
z

array(['1', '2', '3', 'a'], dtype='<U11')

In [10]:
# bütün int. float a dönüştürülecek.
# bütün elemanlar genel olana dönüştürülür!
b = np.array([1,2,3,4.5])

In [11]:
b

array([1. , 2. , 3. , 4.5])

In [13]:
c = np.array([1,2,3,4.5,"2"])

In [14]:
c

array(['1', '2', '3', '4.5', '2'], dtype='<U32')

# Array Data Tipini Manuel Belirtmek 

In [15]:
x = np.array([1,2,3,4.6], dtype="int32")

In [16]:
x

array([1, 2, 3, 4])

In [17]:
y = np.array([1,2,3,4.6], dtype="str")

In [18]:
y

array(['1', '2', '3', '4.6'], dtype='<U3')

In [19]:
z = np.array(["a"], dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [20]:
z2 = np.array(["5"], dtype="int32")

In [21]:
z2

array([5])

# Zero Array 

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

# Multidimensional Array 


In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# parametre olarak shape ve type bilgisi istiyor. bu yüzden hata alıyoruz.
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [26]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# 3 boyutlu array 
# [8,8]'lik 3 adet array oluşturur.
np.zeros([3,5,8])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [29]:
np.zeros(2, dtype=int)

array([0, 0])

In [30]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [33]:
np.zeros((4,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

# Belirli Bir Elemandan Array Oluşturmak

In [40]:
import random
np.full((4,5), random.random())

array([[0.75895966, 0.75895966, 0.75895966, 0.75895966, 0.75895966],
       [0.75895966, 0.75895966, 0.75895966, 0.75895966, 0.75895966],
       [0.75895966, 0.75895966, 0.75895966, 0.75895966, 0.75895966],
       [0.75895966, 0.75895966, 0.75895966, 0.75895966, 0.75895966]])

In [41]:
np.full(4,5)

array([5, 5, 5, 5])

In [42]:
np.full((3,4), "a")

array([['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a']], dtype='<U1')

In [43]:
np.full((3,4), 5.2)

array([[5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2]])

In [47]:
np.full((4,5), 5.2, dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [48]:
np.full((4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

# Ardışık Sayılardan Array Oluşturmak

[0,12)

In [49]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [52]:
np.arange(2,12,-2)

array([], dtype=int32)

In [54]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

# Aralığı Eşit Uzaklıktaki Noktalara Bölmek

In [56]:
# default olarak 50 noktaya böler. başlangıc ve bitis bu 50 noktanın içerisinde 
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [57]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [ ]:
# endpoint = bitis elemanını dahil edip etmeyeceğimiz
np.linspace(1,2,num=3, endpoint=False)

In [61]:
np.linspace(1,2, num=30)

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

In [62]:
np.linspace(1.5, 4.7, 3)

array([1.5, 3.1, 4.7])

# Normal Distribution'dan Çekilmiş Değerler İle Array Oluşturmak

. (mean, std, array size)

In [63]:
np.random.normal(0,1, (4,5))

array([[ 0.50836543, -1.73328436, -0.06657061,  0.63097307,  0.4470856 ],
       [ 0.05579874, -0.60144116, -0.36236034, -0.98308817,  0.26160197],
       [-0.17439709, -0.15643972,  0.86537806, -0.49667072, -0.53662298],
       [ 0.29121775, -1.32694799,  0.6281414 , -2.87865162,  0.64305213]])

In [64]:
np.random.normal(0,100, (4,5))

array([[   6.55542344,  -61.94180848,  -68.12192733, -129.3677734 ,
          51.57546229],
       [ -24.37069996,   31.35628108,   45.25451382,   76.89043088,
         -25.93009552],
       [ -28.4960207 ,   23.01033593,   35.53214899,  176.97768232,
         -15.63571894],
       [ -49.39750889, -134.66468149,  -54.88987545,  -76.79458328,
         -55.68107895]])

In [65]:
np.random.normal(10, 100, (4,5))

array([[  12.96167956,  -48.58494511,  -24.05435072,  254.92250363,
           2.12521855],
       [ -20.68710563,   16.5387886 ,  -80.3758566 ,   91.64543411,
         -68.12116085],
       [  53.06419812,  195.27971026,   48.20429521,  -19.3577691 ,
          85.61300374],
       [  42.84211929, -202.23761891,   67.47464332,   89.25470583,
          98.82199008]])

# Random Integer'lar İle Array Oluşturmak 

In [68]:
# bitis dahil edilmez
np.random.randint(1, 10, (3,4))

array([[1, 6, 5, 9],
       [5, 4, 7, 4],
       [4, 2, 4, 5]])

In [70]:
np.random.randint(1,10,(3,8,5))

array([[[2, 4, 9, 3, 8],
        [9, 9, 3, 5, 3],
        [8, 8, 3, 2, 7],
        [9, 1, 4, 5, 2],
        [2, 8, 7, 9, 6],
        [7, 3, 5, 5, 1],
        [3, 5, 2, 2, 6],
        [5, 7, 1, 6, 8]],

       [[1, 2, 1, 8, 3],
        [7, 2, 3, 4, 7],
        [3, 4, 9, 2, 3],
        [1, 5, 6, 3, 6],
        [5, 4, 5, 6, 5],
        [1, 1, 6, 5, 8],
        [9, 5, 3, 7, 6],
        [9, 2, 4, 7, 8]],

       [[3, 5, 3, 1, 8],
        [9, 5, 6, 1, 8],
        [3, 5, 6, 2, 1],
        [3, 1, 1, 7, 4],
        [4, 3, 4, 5, 4],
        [6, 4, 2, 6, 8],
        [1, 9, 8, 2, 1],
        [3, 2, 7, 3, 6]]])

In [75]:
np.random.randint(1,4)

2

In [76]:
d = {}

for _ in range(20000):
    val = np.random.randint(1,11)
    
    if val not in d: 
        d[val] = 1
    else: 
        d[val] +=1

In [77]:
d

{9: 1966,
 4: 2034,
 7: 1970,
 1: 2003,
 2: 1978,
 6: 1993,
 10: 2028,
 3: 2012,
 8: 2012,
 5: 2004}

# Identity (birim) Matrix Oluşturmak

In [78]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [80]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])